import { and, eq } from "drizzle-orm";
import { CreditCard } from "lucide-react";
import { DashboardPage } from "@/components/dashboard-page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { requireDb } from "@/db";
import { subscriptions, usageMonths } from "@/db/schema";
import { checkoutAction, portalAction } from "@/features/billing/actions";
import { requirePageWorkspace } from "@/lib/page-auth";
import { isPaidPlan, planCatalog } from "@/lib/plans";

export default async function Page(){const context=await requirePageWorkspace();if(!context)return <DashboardPage title="Facturation" description="Configuration requise."><></></DashboardPage>;const month=new Date().toISOString().slice(0,7);const [subscription,usage]=await Promise.all([requireDb().select().from(subscriptions).where(eq(subscriptions.workspaceId,context.workspace.id)).limit(1).then((rows)=>rows[0]),requireDb().select().from(usageMonths).where(and(eq(usageMonths.workspaceId,context.workspace.id),eq(usageMonths.month,month))).limit(1).then((rows)=>rows[0])]);const plan=isPaidPlan(context.workspace.plan)?planCatalog[context.workspace.plan]:null;const accepted=usage?.acceptedEmails??0;const overage=plan?Math.max(0,accepted-plan.includedEmails):0;const estimate=plan?overage/1000*plan.overageCentsPerThousand/100:0;return <DashboardPage title="Facturation" description="Abonnement et usage réellement accepté par SES."><div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><article className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><div><Badge>{plan?.name??"Sandbox"}</Badge><p className="mt-3 text-3xl font-semibold">{plan?`${plan.monthlyPriceCents/100} € HT / mois`:"Aucun abonnement"}</p><p className="mt-2 text-sm text-muted-foreground">Statut Stripe : {subscription?.status??"inactive"}</p></div><CreditCard className="text-primary"/></div>{plan&&<><div className="mt-8 flex justify-between text-sm"><span>{accepted.toLocaleString("fr-FR")} emails</span><span>{plan.includedEmails.toLocaleString("fr-FR")} inclus</span></div><Progress value={Math.min(100,accepted/plan.includedEmails*100)} className="mt-3"/><p className="mt-3 text-xs text-amber-700">{overage.toLocaleString("fr-FR")} emails en dépassement · estimation {estimate.toFixed(2).replace(".",",")} € HT</p></>}</article><article className="rounded-2xl border bg-white p-6"><h2 className="font-semibold">Gérer l’abonnement</h2>{subscription?.stripeCustomerId?<form action={portalAction}><Button className="mt-6" type="submit" variant="outline">Ouvrir le portail Stripe</Button></form>:<p className="mt-3 text-sm text-muted-foreground">Choisissez un forfait pour ouvrir Stripe Checkout.</p>}</article></div><div className="mt-6 grid gap-4 md:grid-cols-3">{Object.entries(planCatalog).map(([id,item])=><article className="rounded-2xl border bg-white p-5" key={id}><h2 className="font-semibold">{item.name}</h2><p className="mt-2 text-2xl font-semibold">{item.monthlyPriceCents/100} €</p><p className="mt-2 text-sm text-muted-foreground">{item.includedEmails.toLocaleString("fr-FR")} emails inclus</p><form action={checkoutAction.bind(null,id)}><Button className="mt-5 w-full" type="submit" variant={context.workspace.plan===id?"secondary":"default"}>Choisir {item.name}</Button></form></article>)}</div></DashboardPage>}
