import type { SQSEvent, SQSBatchResponse } from "aws-lambda";
import { SQSClient, SendMessageBatchCommand } from "@aws-sdk/client-sqs";
import { and, eq } from "drizzle-orm";
import { requireDb } from "@/db";
import { emailEvents, messages, suppressions, webhookDeliveries, webhookEndpoints } from "@/db/schema";
import { suppressionHash } from "@/features/contacts/normalization";

const statusByType:Record<string,typeof messages.$inferInsert.status>={DELIVERY:"delivered",BOUNCE:"hard_bounced",COMPLAINT:"complained",SEND:"sent",REJECT:"failed"};
export async function handler(event:SQSEvent):Promise<SQSBatchResponse>{const failed=[];for(const record of event.Records){try{await ingest(record.body)}catch{failed.push({itemIdentifier:record.messageId})}}return{batchItemFailures:failed}}
async function ingest(body:string){const envelope=JSON.parse(body) as {id?:string;detail?:Record<string,unknown>;detailType?:string};const detail=(envelope.detail??envelope) as Record<string,unknown>;const mail=(detail.mail??{}) as {messageId?:string;tags?:Record<string,string[]>;timestamp?:string};const eventId=envelope.id??String(detail.eventId??crypto.randomUUID());const sesId=mail.messageId??String(detail.mailMessageId??"");const [message]=await requireDb().select().from(messages).where(eq(messages.sesMessageId,sesId)).limit(1);if(!message)return;const type=String(detail.eventType??detail.eventTypeName??envelope.detailType??"UNKNOWN").toUpperCase();const customerType=type==="DELIVERY"?"delivered":type==="BOUNCE"?"bounced":type==="COMPLAINT"?"complained":type==="SEND"?"sent":type.toLowerCase();const status=statusByType[type];const db=requireDb();const deliveryIds:string[]=[];await db.transaction(async tx=>{const inserted=await tx.insert(emailEvents).values({workspaceId:message.workspaceId,messageId:message.id,externalEventId:eventId,type:customerType,occurredAt:new Date(mail.timestamp??Date.now()),payload:detail}).onConflictDoNothing().returning();if(!inserted.length)return;if(status)await tx.update(messages).set({status,deliveredAt:status==="delivered"?new Date():message.deliveredAt,updatedAt:new Date()}).where(eq(messages.id,message.id));if(status==="hard_bounced"||status==="complained")await tx.insert(suppressions).values({workspaceId:message.workspaceId,normalizedEmail:message.toEmail,emailHash:suppressionHash(message.toEmail),reason:status==="complained"?"complaint":"hard_bounce",sourceMessageId:message.id}).onConflictDoNothing();const endpoints=await tx.select().from(webhookEndpoints).where(and(eq(webhookEndpoints.workspaceId,message.workspaceId),eq(webhookEndpoints.enabled,true)));for(const endpoint of endpoints)if(endpoint.eventTypes.includes(customerType)){const [delivery]=await tx.insert(webhookDeliveries).values({endpointId:endpoint.id,eventId:inserted[0].id,nextAttemptAt:new Date()}).onConflictDoNothing().returning();if(delivery)deliveryIds.push(delivery.id)}});const url=process.env.WEBHOOK_QUEUE_URL;if(url&&deliveryIds.length){const sqs=new SQSClient({});for(let i=0;i<deliveryIds.length;i+=10)await sqs.send(new SendMessageBatchCommand({QueueUrl:url,Entries:deliveryIds.slice(i,i+10).map((deliveryId,j)=>({Id:String(i+j),MessageBody:JSON.stringify({deliveryId})}))}))}}
