import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, Braces, Check, FileCheck2, LockKeyhole, Radar, ShieldCheck, Sparkles } from "lucide-react";
import { MarketingFooter } from "@/components/marketing-footer";
import { MarketingHeader } from "@/components/marketing-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const benefits=[
  {icon:Braces,title:"Une API, un événement, un destinataire",text:"Un contrat HTTP strict, une clé Yodev et une idempotence obligatoire. Aucun compte fournisseur à créer."},
  {icon:FileCheck2,title:"Cas d’usage et templates approuvés",text:"Chaque application, catégorie transactionnelle et modèle est relu avant le premier envoi live."},
  {icon:Radar,title:"Délivrabilité opérée",text:"Yodev prépare le DNS, normalise les événements et surveille bounces, plaintes, suppressions et files."},
  {icon:ShieldCheck,title:"Garde-fous automatiques",text:"Quotas progressifs, suspension immédiate à la première plainte et aucune relance après un résultat ambigu."},
];

export const metadata:Metadata={alternates:{canonical:"https://mail.yodev.fr"}};
export default function Home(){return <><MarketingHeader/><main>
  <section className="relative overflow-hidden px-5 pb-24 pt-20 sm:pt-28"><div className="mx-auto max-w-6xl text-center"><Badge variant="secondary" className="mb-7 border border-primary/15 bg-primary/5 text-primary"><Sparkles className="mr-1 size-3"/> Bêta privée · Sur dossier</Badge><h1 className="mx-auto max-w-4xl text-balance text-5xl font-semibold tracking-[-.045em] sm:text-7xl">Vos emails transactionnels.<br/><span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">L’infrastructure en moins.</span></h1><p className="mx-auto mt-7 max-w-2xl text-balance text-lg leading-8 text-muted-foreground sm:text-xl">Mail by Yodev vérifie les domaines de vos applications, opère la livraison et vous expose une API unique. Un appel correspond à un événement applicatif et à un destinataire.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 px-6"><Link href="/inscription">Candidater à la bêta <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline" className="h-12 bg-white"><Link href="/docs">Explorer l’API</Link></Button></div><div className="mx-auto mt-14 max-w-5xl rounded-[2rem] border bg-[#0C1117] p-3 text-left shadow-2xl shadow-blue-900/15"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-6 text-white sm:p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-white/55">Flux transactionnel</p><p className="mt-1 text-xl font-medium">payment_receipt</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-300">● Domaine vérifié</span></div><div className="mt-8 grid gap-3 sm:grid-cols-4">{[["Destinataires","1 / requête"],["Tracking","Désactivé"],["Template","Approuvé"],["Statut","Délivré"]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/8 bg-white/[.04] p-4"><p className="text-xs text-white/45">{a}</p><p className="mt-2 text-lg font-medium">{b}</p></div>)}</div></div></div></div></section>
  <section className="border-y bg-white/70 px-5 py-24"><div className="mx-auto max-w-6xl"><p className="text-sm font-medium text-primary">UNE PASSERELLE GÉRÉE</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight">Vos clients gardent leur domaine. Yodev prend en charge le setup et l’exploitation.</h2><div className="mt-12 grid gap-5 md:grid-cols-2">{benefits.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border bg-background p-7 shadow-sm"><span className="inline-flex rounded-xl bg-primary/10 p-3 text-primary"><Icon/></span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section>
  <section className="px-5 py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><div><Badge>29 € HT / mois</Badge><h2 className="mt-5 text-4xl font-semibold tracking-tight">Une bêta accompagnée, sans compte technique à déléguer.</h2><p className="mt-4 leading-7 text-muted-foreground">Deux domaines, trois membres, puis 2,50 € HT par 1 000 emails acceptés pour livraison. Aucun email simulé ou refusé avant acceptation n’est facturé.</p><ul className="mt-7 grid gap-3 text-sm">{["Validation manuelle avant clé live","Accompagnement DNS inclus","Pièces jointes contrôlées et temporaires"].map((item)=><li key={item} className="flex gap-2"><Check className="size-5 text-emerald-600"/>{item}</li>)}</ul><Button asChild className="mt-8" variant="outline"><Link href="/tarifs">Voir le tarif bêta</Link></Button></div><div className="rounded-3xl border bg-white p-8 shadow-xl"><LockKeyhole className="size-7 text-primary"/><p className="mt-5 text-sm text-muted-foreground">Accès plateforme</p><p className="mt-2 text-5xl font-semibold">29 €<span className="text-base font-normal text-muted-foreground"> HT / mois</span></p><div className="my-7 h-px bg-border"/><p className="text-sm text-muted-foreground">Usage mesuré</p><p className="mt-2 text-2xl font-medium">0,0025 € / email accepté</p></div></div></section>
  <section className="px-5 pb-24"><div className="mx-auto max-w-6xl rounded-[2rem] bg-[#0C1117] px-7 py-16 text-center text-white"><h2 className="text-4xl font-semibold">Décrivez votre premier flux transactionnel.</h2><p className="mx-auto mt-4 max-w-xl text-white/60">Les premiers workspaces sont examinés et accompagnés à la main.</p><Button asChild size="lg" className="mt-8 bg-white text-black hover:bg-white/90"><Link href="/inscription">Candidater à la bêta <ArrowRight/></Link></Button></div></section>
</main><MarketingFooter/></>}
