import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
const pages:Record<string,{title:string;intro:string;sections:Array<[string,string]>}>={
  "anti-abus":{title:"Politique anti-abus",intro:"VigieMail protège la réputation collective par des règles strictes et vérifiables.",sections:[["Usages interdits","Cold email, scraping, listes achetées, phishing, usurpation et contenu frauduleux sont interdits."],["Contrôles","Les nouveaux workspaces sont approuvés manuellement, soumis à un warm-up et peuvent être suspendus automatiquement selon leurs signaux."],["Signalement","Les signalements d'abus seront traités en priorité via abuse@vigie-mail.fr."]]},
  confidentialite:{title:"Politique de confidentialité",intro:"Les principes de traitement des données de VigieMail.",sections:[["Responsabilités","VigieMail agit comme sous-traitant pour les contacts de ses clients et responsable de traitement pour ses propres comptes."],["Hébergement","Les données applicatives sont hébergées dans l'Union européenne. Amazon SES traite les envois dans la région de Paris."],["Conservation","Le contenu des emails est supprimé après 30 jours par défaut, les événements analytiques après 13 mois et les logs opérationnels après 90 jours."]]},
  cgu:{title:"Conditions générales d'utilisation",intro:"Cadre contractuel de la bêta privée VigieMail.",sections:[["Accès","L'accès à la bêta est soumis à validation manuelle et au respect de la politique anti-abus."],["Responsabilité","Le client demeure responsable de la licéité de ses destinataires, contenus et bases légales."],["Suspension","VigieMail peut suspendre un envoi ou un workspace afin de protéger les destinataires et la réputation de la plateforme."]]},
  "mentions-legales":{title:"Mentions légales",intro:"Informations relatives à l'éditeur de VigieMail.",sections:[["Éditeur","Informations société, SIREN, adresse et directeur de publication à compléter avant ouverture publique."],["Hébergement","Vercel Inc. pour l'application, Neon pour la base de données et Amazon Web Services EMEA SARL pour le transport email."],["Contact","contact@vigie-mail.fr — abuse@vigie-mail.fr"]]},
};
export function generateStaticParams(){return Object.keys(pages).map(legal=>({legal}))}
export default async function Page({params}:{params:Promise<{legal:string}>}){const {legal}=await params;const page=pages[legal];if(!page)notFound();return <PageShell eyebrow="Informations légales" title={page.title} intro={page.intro}><div className="mx-auto grid max-w-3xl gap-8">{page.sections.map(([title,text])=><section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></section>)}<p className="rounded-xl border bg-amber-50 p-4 text-sm text-amber-900">Version de travail à faire valider par un juriste avant ouverture publique.</p></div></PageShell>}
