import { notFound } from "next/navigation";
import { PageShell } from "@/components/page-shell";
const pages:Record<string,{title:string;intro:string;sections:Array<[string,string]>}>={
  "anti-abus":{title:"Politique anti-abus",intro:"Mail by Yodev protège la réputation collective par des règles strictes et vérifiables.",sections:[["Usages interdits","Cold email, scraping, listes achetées, phishing, usurpation et contenu frauduleux sont interdits."],["Contrôles","Les nouveaux workspaces sont approuvés manuellement, soumis à un warm-up et peuvent être suspendus automatiquement selon leurs signaux."],["Signalement","Les signalements d'abus seront traités en priorité via hello@yodev.fr."]]},
  confidentialite:{title:"Politique de confidentialité",intro:"Les principes de traitement des données de Mail by Yodev.",sections:[["Responsable du traitement","Yodev, édité par Yoann Andrieux, entrepreneur individuel (EI), SIREN 803 272 590, est responsable du traitement des données de ses propres utilisateurs. Les demandes relatives aux droits peuvent être adressées à hello@yodev.fr."],["Responsabilités","Mail by Yodev agit comme sous-traitant pour les contacts de ses clients et responsable de traitement pour ses propres comptes."],["Hébergement","Les données applicatives sont hébergées dans l'Union européenne. Amazon SES traite les envois dans la région de Paris."],["Conservation","Le contenu des emails est supprimé après 30 jours par défaut, les événements analytiques après 13 mois et les logs opérationnels après 90 jours."]]},
  cgu:{title:"Conditions générales d'utilisation",intro:"Cadre contractuel de la bêta privée Mail by Yodev.",sections:[["Accès","L'accès à la bêta est soumis à validation manuelle et au respect de la politique anti-abus."],["Responsabilité","Le client demeure responsable de la licéité de ses destinataires, contenus et bases légales."],["Suspension","Mail by Yodev peut suspendre un envoi ou un workspace afin de protéger les destinataires et la réputation de la plateforme."]]},
  "mentions-legales":{title:"Mentions légales",intro:"Informations relatives à l'éditeur de Mail by Yodev.",sections:[["Éditeur","Mail by Yodev est édité sous le nom commercial Yodev par Yoann Andrieux, entrepreneur individuel (EI)."],["Immatriculation et activité","SIREN : 803 272 590. SIRET : 803 272 590 00024. Activité principale : programmation informatique (code NAF/APE 62.01Z)."],["Régime de TVA","TVA non applicable, article 293 B du Code général des impôts."],["Adresse professionnelle","11 rue de la Chine, 75020 Paris, France."],["Directeur de la publication","Yoann Andrieux."],["Contact","hello@yodev.fr"],["Hébergement","L'application est hébergée par Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, États-Unis. Neon fournit l'hébergement de la base de données et Amazon Web Services EMEA SARL assure le transport des emails."]]},
};
export function generateStaticParams(){return Object.keys(pages).map(legal=>({legal}))}
export default async function Page({params}:{params:Promise<{legal:string}>}){const {legal}=await params;const page=pages[legal];if(!page)notFound();return <PageShell eyebrow="Informations légales" title={page.title} intro={page.intro}><div className="mx-auto grid max-w-3xl gap-8">{page.sections.map(([title,text])=><section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></section>)}<p className="text-sm text-muted-foreground">Dernière mise à jour : 10 août 2026.</p></div></PageShell>}
