import { desc } from "drizzle-orm";
import { AlertTriangle, Check, Pause, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { requireDb } from "@/db";
import { workspaces } from "@/db/schema";
import { reviewWorkspaceAction } from "@/features/admin/actions";
import { requireAdmin } from "@/lib/page-auth";
export default async function Page(){await requireAdmin();const rows=await requireDb().select().from(workspaces).orderBy(desc(workspaces.createdAt));return <main className="mx-auto min-h-screen max-w-6xl p-8"><p className="text-sm font-semibold text-primary">CONSOLE INTERNE</p><h1 className="mt-2 text-3xl font-semibold">Validation des workspaces</h1><p className="mt-2 text-muted-foreground">Métadonnées anti-abus uniquement, sans accès implicite au contenu des emails.</p><div className="mt-8 grid gap-4">{rows.map((workspace)=><article className="rounded-2xl border bg-white p-6" key={workspace.id}><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex gap-3"><h2 className="font-semibold">{workspace.name}</h2><Badge variant={workspace.status==="rejected"?"destructive":"secondary"}>{workspace.status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{workspace.websiteUrl??"Site non renseigné"} · {workspace.expectedMonthlyVolume.toLocaleString("fr-FR")} emails/mois</p><p className="mt-3 max-w-2xl whitespace-pre-wrap text-sm">{workspace.useCase??"Cas d’usage non renseigné"}</p></div><div className="flex flex-wrap gap-2"><form action={reviewWorkspaceAction.bind(null,workspace.id,"approved")}><Button size="sm" type="submit"><Check/>Approuver</Button></form><form action={reviewWorkspaceAction.bind(null,workspace.id,"limited")}><Button size="sm" type="submit" variant="outline"><Pause/>Limiter</Button></form><form action={reviewWorkspaceAction.bind(null,workspace.id,"rejected")}><Button size="sm" type="submit" variant="destructive"><X/>Refuser</Button></form></div></div>{workspace.status==="pending_review"&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="mr-2 inline size-4"/>Vérifier le site et demander une preuve de collecte avant approbation.</p>}</article>)}{!rows.length&&<p className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">Aucun workspace.</p>}</div></main>}
