import Link from "next/link";
import { Activity, BookOpen, CreditCard, Globe2, KeyRound, LayoutDashboard, Mail, Settings, Shield, Users, Workflow } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { Badge } from "@/components/ui/badge";
import type { Locale } from "@/i18n/config";
import { localized, localizedPath } from "@/i18n/config";
import { statusLabel } from "@/i18n/format";

export function DashboardSidebar({locale,plan,workspaceName}:{locale:Locale;plan:string;workspaceName:string}){
  const copy=localized(locale,{fr:{overview:"Vue d’ensemble",useCases:"Cas d’usage",templates:"Templates",domains:"Domaines",members:"Membres",keys:"Clés API",deliverability:"Délivrabilité",billing:"Facturation",settings:"Paramètres",admin:"Administration"},en:{overview:"Overview",useCases:"Use cases",templates:"Templates",domains:"Domains",members:"Members",keys:"API keys",deliverability:"Deliverability",billing:"Billing",settings:"Settings",admin:"Administration"}});
  const items=[[LayoutDashboard,copy.overview,"/dashboard"],[Mail,"Emails","/dashboard/emails"],[Workflow,copy.useCases,"/dashboard/profils"],[Mail,copy.templates,"/dashboard/templates"],[Globe2,copy.domains,"/dashboard/domaines"],[Users,copy.members,"/dashboard/membres"],[KeyRound,copy.keys,"/dashboard/api-keys"],[Activity,copy.deliverability,"/dashboard/delivrabilite"],[Workflow,"Webhooks","/dashboard/webhooks"]] as const;
  const href=(path:string)=>localizedPath(locale,path);
  return <aside className="hidden w-64 shrink-0 border-r bg-[#17151f] text-white lg:flex lg:flex-col"><div className="flex h-16 items-center border-b border-white/10 px-5"><BrandMark className="text-lg"/></div><div className="p-4"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-xs text-white/45">WORKSPACE</p><div className="mt-2 flex items-center justify-between gap-2 text-sm"><span className="truncate">{workspaceName}</span><Badge className="bg-amber-400/10 text-amber-300">{plan === "pilote" ? (locale === "fr" ? "pilote" : "pilot") : statusLabel(locale,plan)}</Badge></div></div></div><nav className="grid gap-1 px-3">{items.map(([Icon,label,path])=><Link key={path} href={href(path)} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-white/65 transition hover:bg-white/8 hover:text-white"><Icon className="size-4"/>{label}</Link>)}</nav><div className="mt-auto grid gap-1 border-t border-white/10 p-3"><Link href={href("/docs")} className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-white/60"><BookOpen className="size-4"/>Documentation</Link><Link href={href("/dashboard/facturation")} className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-white/60"><CreditCard className="size-4"/>{copy.billing}</Link><Link href={href("/dashboard/parametres")} className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-white/60"><Settings className="size-4"/>{copy.settings}</Link><Link href={href("/admin")} className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-white/60"><Shield className="size-4"/>{copy.admin}</Link></div></aside>}
