"use client";
import { useActionState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createWebhookFormAction } from "@/features/webhooks/actions";
import type { Locale } from "@/i18n/config";
import { localized } from "@/i18n/config";
export function WebhookForm({locale}:{locale:Locale}){const [state,action,pending]=useActionState(createWebhookFormAction,{secret:"",error:""});const events=["email.queued","email.sent","email.delivered","email.soft_bounced","email.hard_bounced","email.complained","email.failed","email.suppressed"];const copy=localized(locale,{fr:{add:"Ajouter l’endpoint",once:"Secret affiché une seule fois",help:"Copiez-le avant de recharger la page. L’endpoint apparaîtra dans la liste après le rechargement."},en:{add:"Add endpoint",once:"Secret displayed only once",help:"Copy it before reloading the page. The endpoint will appear in the list after reload."}});return <div className="rounded-2xl border bg-white p-5"><form action={action} className="grid gap-4"><Input name="url" placeholder="https://client.com/webhooks/yodev-mail" type="url" required/><div className="flex flex-wrap gap-4 text-sm">{events.map((event)=><label className="flex gap-1.5" key={event}><input defaultChecked name="eventTypes" type="checkbox" value={event}/>{event}</label>)}</div><Button className="w-fit" disabled={pending} type="submit"><Plus/>{copy.add}</Button></form>{state.secret&&<div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>{copy.once}</strong><code className="mt-2 block break-all text-xs">{state.secret}</code><p className="mt-2 text-xs">{copy.help}</p></div>}{state.error&&<p className="mt-3 text-sm text-destructive">{state.error}</p>}</div>}
