import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { requireDb } from "@/db";
import { contacts, consentEvents, suppressions } from "@/db/schema";
import { suppressionHash } from "@/features/contacts/normalization";
import { env } from "@/lib/env";
import { verifyExpiringToken } from "@/lib/crypto";

async function unsubscribe(token:string){if(!env.UNSUBSCRIBE_SIGNING_SECRET)return null;const payload=verifyExpiringToken(token,env.UNSUBSCRIBE_SIGNING_SECRET);if(!payload?.workspaceId||!payload.contactId)return null;const db=requireDb();const [contact]=await db.select().from(contacts).where(and(eq(contacts.id,payload.contactId),eq(contacts.workspaceId,payload.workspaceId))).limit(1);if(!contact)return null;await db.transaction(async tx=>{await tx.update(contacts).set({status:"unsubscribed",marketingConsent:false,unsubscribedAt:new Date(),updatedAt:new Date()}).where(eq(contacts.id,contact.id));await tx.insert(suppressions).values({workspaceId:contact.workspaceId,normalizedEmail:contact.normalizedEmail,emailHash:suppressionHash(contact.email),reason:"unsubscribe"}).onConflictDoNothing();await tx.insert(consentEvents).values({workspaceId:contact.workspaceId,contactId:contact.id,kind:"marketing",action:"withdrawn",source:"one_click"})});return contact}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){const contact=await unsubscribe((await params).token);if(request.headers.get("content-type")?.includes("application/x-www-form-urlencoded"))return new NextResponse(page(contact?"Vous êtes désabonné":"Lien invalide ou expiré",false),{status:contact?200:400,headers:{"content-type":"text/html; charset=utf-8"}});return contact?NextResponse.json({success:true}):NextResponse.json({error:"Lien invalide ou expiré"},{status:400})}
export async function GET(_:Request,{params}:{params:Promise<{token:string}>}){const token=(await params).token;const secret=env.UNSUBSCRIBE_SIGNING_SECRET;const valid=secret&&verifyExpiringToken(token,secret);if(!valid)return new NextResponse(page("Lien invalide ou expiré",false),{status:400,headers:{"content-type":"text/html; charset=utf-8"}});return new NextResponse(page("Gérer mes préférences",true,token),{headers:{"content-type":"text/html; charset=utf-8"}})}
function page(title:string,form:boolean,token=""){return `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title} — Mail by Yodev</title><body style="font-family:system-ui;background:#f8f7fb;padding:32px;color:#18151f"><main style="max-width:520px;margin:10vh auto;background:white;border:1px solid #e6e3eb;border-radius:24px;padding:32px"><h1>${title}</h1>${form?`<p>Confirmez pour ne plus recevoir les communications marketing de cet expéditeur.</p><form method="post" action="/u/${token}"><button style="background:#315efb;color:white;border:0;border-radius:10px;padding:12px 18px;font-weight:600">Me désabonner</button></form>`:"<p>Ce lien ne peut plus être utilisé.</p>"}<p style="margin-top:28px;color:#777;font-size:12px">Propulsé par Mail by Yodev</p></main></body></html>`}
